# site properties and page defaults
title: Communication and Computation Lab
subtitle: School of Communication, Ohio State University
description: Communication and Computation Lab
header: images/OSU_background.jpg
footer: images/OSU_background.jpg
proofer: false
# 添加网站URL配置
url: "https://wocqcm2.github.io"
baseurl: "/Communication-and-Computation-Lab"

# GitHub Pages元数据配置，防止用户名覆盖网站标题
github:
  source:
    branch: gh-pages
  repository_name: Communication-and-Computation-Lab
  repository_url: "https://github.com/wocqcm2/Communication-and-Computation-Lab"

# site social media and other links
links:
  email: meng.28@osu.edu
  google-scholar: MDKCNTsAAAAJ
  twitter: jingbomeng
### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
