# 这个文件可以添加自定义的文章引用
# 以下是一个示例格式，当前已清空所有模板文章
# 系统将使用ORCID来获取发表文章

# 排除无效的Web of Science记录
- id: wosuid:WOS:000825875706068
  remove: true

- id: wosuid:WOS:000625875706068
  remove: true

- id: wosuid:PPRN:14763802
  remove: true

- id: wosuid:PPRN:22913350
  remove: true

# 为文章添加期刊封面图片
- id: doi:10.1080/10447318.2024.2404262
  image: images/publications/International-Journal-of-Human–Computer-Interaction.jpg

- id: doi:10.1145/3579505
  image: images/publications/Proceedings-of-the-ACM-on-Human-Computer-Interaction.png

- id: doi:10.1016/J.CHB.2022.107594
  image: images/publications/Computers-in-Human-Behavior.png

- id: doi:10.1093/jcmc/zmac034
  image: images/publications/journal-of-computer-mediated-communication.jpg

# 示例：
# - id: doi:10.xxxx/xxxxx
#   type: paper
#   image: https://example.com/image.jpg
#   tags:
#     - tag1
#     - tag2

# 2022年文章
- id: doi:10.1002/9781119678816.IEHC0587
  image: images/publications/The-International-Encyclopedia-of-Health-Communication.jpg
  
- id: doi:10.1080/1369118X.2022.2085615
  image: images/publications/Information-Communication-&-Society.jpg

- id: doi:10.3390/IJERPH19116759
  image: images/publications/International-Journal-of-Environmental-Research-and-Public-Health.jpg

# 2021年文章
- id: doi:10.1027/1864-1105/A000309
  image: images/publications/Journal-of-Media-Psychology.png

- id: doi:10.1093/jcmc/zmab005
  image: images/publications/journal-of-computer-mediated-communication.jpg

- id: doi:10.1002/HBE2.258
  image: images/publications/Human-Behavior-and-Emerging-Technologies.jpg

# 2020年文章
- id: doi:10.1080/10410236.2020.1853327
  image: images/publications/Health-Communication.jpg

- id: doi:10.1037/pag0000569
  image: images/publications/Psychology-and-Aging.jpg

- id: doi:10.1016/J.CHB.2019.106181
  image: images/publications/Computers-in-Human-Behavior.png

- id: doi:10.1093/jcmc/zmz030
  image: images/publications/journal-of-computer-mediated-communication.jpg

# 2019年文章
- id: doi:10.1080/10410236.2019.1673947
  image: images/publications/Health-Communication.jpg

- id: doi:10.1080/10410236.2019.1598616
  image: images/publications/Health-Communication.jpg

# 2018年文章
- id: doi:10.1016/J.CHB.2018.07.039
  image: images/publications/Computers-in-Human-Behavior.png

- id: doi:10.1080/01463373.2018.1515782
  image: images/publications/Communication-Quarterly.jpg

- id: doi:10.2196/10139
  image: images/publications/Journal-of-Medical-Internet-Research.jpg

- id: doi:10.1177/2050157918761491
  image: images/publications/Mobile-Media-&-Communication.jpg

- id: doi:10.2196/preprints.10139
  image: images/publications/JMIR-Publications-Inc.png

# 2017年文章
- id: doi:10.2196/jmir.6537
  image: images/publications/Journal-of-Medical-Internet-Research.jpg

- id: doi:10.1186/s13012-017-0542-7
  image: images/publications/Implementation-Science.jpg

- id: doi:10.1089/cyber.2016.0325
  image: images/publications/Cyberpsychology-Behavior-and-Social-Networking.jpg

# 2016年文章
- id: doi:10.1111/jcom.12268
  image: images/publications/Journal-of-Communication.jpg

- id: doi:10.1007/S40615-016-0307-Z
  image: images/publications/Journal-of-Racial-and-Ethnic-Health-Disparities.png

- id: doi:10.1007/s40615-016-0280-6
  image: images/publications/Journal-of-Racial-and-Ethnic-Health-Disparities.png

- id: doi:10.1080/10810730.2016.1153760
  image: images/publications/Journal-of-Health-Communication.jpg

- id: doi:10.1080/10410236.2015.1079760
  image: images/publications/Health-Communication.jpg

- id: doi:10.1080/10410236.2015.1027033
  image: images/publications/Health-Communication.jpg

# 2015年文章
- id: doi:10.1016/j.chb.2015.06.007
  image: images/publications/Computers-in-Human-Behavior.png

- id: doi:10.1016/j.chb.2015.03.018
  image: images/publications/Computers-in-Human-Behavior.png

# 2014年文章
- id: doi:10.1007/978-3-319-07632-4_15
  image: images/publications/Lecture-Notes-in-Computer-Science.jpg

# 2013年文章
- id: doi:10.1177/0093650213476294
  image: images/publications/Communication-Research.jpg

# 2012年文章
- id: doi:10.5210/fm.v17i5.3718
  image: images/publications/First-Monday.png

# 2011年文章
- id: doi:10.1111/j.1460-2466.2011.01543.x
  image: images/publications/Journal-of-Communication.jpg

# 2009年文章
- id: doi:10.1177/0093650209333030
  image: images/publications/Communication-Research.jpg
