name: Build and Deploy Lab Website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Lab Website Docker image
      run: |
        docker build --tag lab-website-renderer:latest --file ./.docker/Dockerfile .
    
    - name: Run cite process to update citations
      run: |
        docker run --rm --volume "$(pwd):/usr/src/app" lab-website-renderer:latest python3 _cite/cite.py
    
    - name: Build Jekyll site
      run: |
        docker run --rm --volume "$(pwd):/usr/src/app" lab-website-renderer:latest bundle exec jekyll build
    
    - name: Git status
      run: |
        git status
    
    - name: Handle citations update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 忽略缓存文件
        git update-index --skip-worktree _cite/.cache/cache.db || true
        
        # 检查citations.yaml是否有更改
        git add _data/citations.yaml
        
        # 如果有更改，提交并推送
        if ! git diff --staged --quiet; then
          git commit -m "Update citations via GitHub Actions"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          echo "Citations updated and pushed."
        else
          echo "No changes to citations.yaml, skipping commit."
        fi
        
        # 恢复对缓存文件的跟踪
        git update-index --no-skip-worktree _cite/.cache/cache.db || true 